[window]

opacity = 0.95

padding.x = 0
padding.y = 0

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "UbuntuMonoNerdFontMono"
bold.family = "UbuntuMonoNerdFontMono"
italic.family = "UbuntuMonoNerdFontMono"
bold_italic.family = "UbuntuMonoNerdFontMono"
size = 15.0
